# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/SR_projekty/reka/centroid_final/centroid_final.cache/wt [current_project]
set_property parent.project_path D:/SR_projekty/reka/centroid_final/centroid_final.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/SR_projekty/reka/delay [current_project]
update_ip_catalog
set_property ip_output_repo d:/SR_projekty/reka/centroid_final/centroid_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet D:/SR_projekty/reka/centroid_final/centroid_final.runs/div_28_20_synth_1/div_28_20.dcp
set_property used_in_implementation false [get_files D:/SR_projekty/reka/centroid_final/centroid_final.runs/div_28_20_synth_1/div_28_20.dcp]
add_files -quiet D:/SR_projekty/reka/centroid_final/centroid_final.runs/div_30_20_synth_1/div_30_20.dcp
set_property used_in_implementation false [get_files D:/SR_projekty/reka/centroid_final/centroid_final.runs/div_30_20_synth_1/div_30_20.dcp]
add_files -quiet D:/SR_projekty/reka/centroid_final/centroid_final.runs/sum_mult_synth_1/sum_mult.dcp
set_property used_in_implementation false [get_files D:/SR_projekty/reka/centroid_final/centroid_final.runs/sum_mult_synth_1/sum_mult.dcp]
add_files -quiet D:/SR_projekty/reka/centroid_final/centroid_final.runs/multi_deelay_0_synth_1/multi_deelay_0.dcp
set_property used_in_implementation false [get_files D:/SR_projekty/reka/centroid_final/centroid_final.runs/multi_deelay_0_synth_1/multi_deelay_0.dcp]
read_verilog -library xil_defaultlib D:/SR_projekty/reka/centroid_final/centroid_final.srcs/sources_1/new/detect_weight_center.v
read_ip -quiet D:/SR_projekty/reka/centroid_final/centroid_final.srcs/sources_1/ip/div_28_20/div_28_20.xci

read_ip -quiet D:/SR_projekty/reka/centroid_final/centroid_final.srcs/sources_1/ip/div_30_20/div_30_20.xci

read_ip -quiet D:/SR_projekty/reka/centroid_final/centroid_final.srcs/sources_1/ip/sum_mult/sum_mult.xci

read_ip -quiet D:/SR_projekty/reka/centroid_final/centroid_final.srcs/sources_1/ip/multi_deelay_0/multi_deelay_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/SR_projekty/reka/centroid_final/centroid_final.srcs/constrs_1/imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc
set_property used_in_implementation false [get_files D:/SR_projekty/reka/centroid_final/centroid_final.srcs/constrs_1/imports/hdmi_vga_zybo_src/Zybo_HDMI.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top detect_weight_center -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef detect_weight_center.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file detect_weight_center_utilization_synth.rpt -pb detect_weight_center_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
