# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/SR_projekty/reka/median/median.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SR_projekty/reka/median/median.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/SR_projekty/reka/median/median.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM.xci
# IP: The module: 'delayLineBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/SR_projekty/reka/median/median.srcs/sources_1/ip/delayLineBRAM/delayLineBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'delayLineBRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
